# permissions for end users to edit etherpadinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: etherpadoperator
    app.kubernetes.io/managed-by: kustomize
  name: etherpadinstance-editor-role
rules:
- apiGroups:
  - etherpad.etherpadinstance.io
  resources:
  - etherpadinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etherpad.etherpadinstance.io
  resources:
  - etherpadinstances/status
  verbs:
  - get
